// swift-tools-version: 6.0

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import PackageDescription
import AppleProductTypes

let package = Package(
    name: "Remote DaVinci",
    platforms: [
        .iOS("17.0")
    ],
    products: [
        .iOSApplication(
            name: "Remote DaVinci",
            targets: ["Controller"],
            bundleIdentifier: "dev.remote-davinci.controller",
            teamIdentifier: "GJ226AMM25",
            displayVersion: "0.1.0",
            bundleVersion: "1",
            supportedDeviceFamilies: [
                .phone,
                .pad
            ],
            supportedInterfaceOrientations: [
                .portrait,
                .landscapeRight,
                .landscapeLeft,
                .portraitUpsideDown(.when(deviceFamilies: [.pad]))
            ],
            additionalInfoPlistContentFilePath: "AdditionalInfo.plist"
        )
    ],
    targets: [
        .executableTarget(
            name: "Controller",
            dependencies: [
                "ControllerCore"
            ],
            path: "Sources/Controller"
        ),
        .target(
            name: "ControllerCore",
            path: "Sources/ControllerCore"
        ),
        .testTarget(
            name: "ControllerTests",
            dependencies: [
                "ControllerCore"
            ]
        )
    ],
    swiftLanguageVersions: [.version("6")]
)